import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Link from 'next/link';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: '每日零售资讯 | HOWSTODAY',
  description: '基于 DeepSeek 的日用百货零售行业即时资讯聚合平台',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh-CN">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen bg-background`}
      >
        <header className="bg-white border-b border-gray-200 sticky top-0 z-50">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-16 flex items-center justify-between">
            <div className="flex items-center gap-2">
              <span className="text-xl font-bold text-primary tracking-tight">HOWSTODAY</span>
              <span className="text-xs bg-accent text-white px-2 py-0.5 rounded-full font-medium">Internal Tool</span>
            </div>
            <nav className="flex gap-4 text-sm font-medium text-gray-600">
              <Link href="/" className="hover:text-primary transition-colors">仪表板</Link>
              <Link href="/history" className="hover:text-primary transition-colors">历史记录</Link>
            </nav>
          </div>
        </header>

        <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
          {children}
        </main>

        <footer className="border-t border-gray-200 mt-12 py-8 text-center text-sm text-muted">
          <p>© {new Date().getFullYear()} HOWSTODAY Import & Export Co., Ltd.</p>
          <p className="mt-1">Generated by DeepSeek AI & Antigravity Agent</p>
        </footer>
      </body>
    </html>
  );
}
